using JetBrains.Application.Parts;
using JetBrains.Lifetimes;
using JetBrains.ProjectModel;
using JetBrains.Rd.Tasks;                                  // RdTask<T>.Successful
using JetBrains.ReSharper.Feature.Services.Protocol;       // ISolution.GetProtocolSolution()
using RiderMcp.Model;                                       // generated by :protocol rdgen

namespace RiderMcp
{
    /// <summary>
    /// Backend host implementing the RD model declared in :protocol
    /// (<see cref="RiderMcpModel"/>). It answers the frontend's backend_status
    /// request and announces backend readiness.
    ///
    /// The generated types (RiderMcpModel, BackendStatus and the
    /// <c>GetRiderMcpModel()</c> accessor) only resolve after rdgen has run, so
    /// the build wires <c>:protocol:rdgen</c> ahead of compilation.
    /// </summary>
    // Container (eager) instantiation on the primary thread: created as the
    // solution container is composed, so the RD handlers are registered when a
    // solution opens (Demand* would never instantiate since nothing requests it).
    [SolutionComponent(Instantiation.ContainerAsyncPrimaryThread)]
    public class RiderMcpHost
    {
        public RiderMcpHost(Lifetime lifetime, ISolution solution)
        {
            var model = solution.GetProtocolSolution().GetRiderMcpModel();

            // Frontend -> backend request handler. SetSync takes a handler that
            // returns the result directly (no RdTask wrapping); the status is
            // built synchronously and cheaply.
            model.GetBackendStatus.SetSync((_, _) => BuildStatus(solution));

            // Backend -> frontend liveness signal.
            model.BackendReadyChanged.Fire(true);
            lifetime.OnTermination(() => model.BackendReadyChanged.Fire(false));
        }

        private static BackendStatus BuildStatus(ISolution solution)
        {
            var projectCount = solution.GetAllProjects().Count;
            var name = solution.Name ?? solution.SolutionFilePath.NameWithoutExtension;
            var version = typeof(RiderMcpHost).Assembly.GetName().Version?.ToString() ?? "unknown";

            // Positional ctor — field order matches the structdef in :protocol:
            // (solutionName, isReady, projectCount, backendVersion).
            return new BackendStatus(name, true, projectCount, version);
        }
    }
}
