using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using JetBrains.Application.Parts;
using JetBrains.Lifetimes;
using JetBrains.Platform.BuildEvents;                      // BuildEvent (resolved diagnostic)
using JetBrains.ProjectModel;
using JetBrains.ProjectModel.Features.SolutionBuilders;    // ISolutionBuilder, build request/target
using JetBrains.Rd.Tasks;                                  // SetSync / SetAsync
using JetBrains.ReSharper.Feature.Services.Protocol;       // ISolution.GetProtocolSolution()
using RiderMcp.Model;                                       // generated by :protocol rdgen

namespace RiderMcp
{
    /// <summary>
    /// Backend host implementing the RD model declared in :protocol
    /// (<see cref="RiderMcpModel"/>). It answers the frontend's backend_status
    /// request and announces backend readiness.
    ///
    /// The generated types (RiderMcpModel, BackendStatus and the
    /// <c>GetRiderMcpModel()</c> accessor) only resolve after rdgen has run, so
    /// the build wires <c>:protocol:rdgen</c> ahead of compilation.
    /// </summary>
    // Container (eager) instantiation on the primary thread: created as the
    // solution container is composed, so the RD handlers are registered when a
    // solution opens (Demand* would never instantiate since nothing requests it).
    [SolutionComponent(Instantiation.ContainerAsyncPrimaryThread)]
    public class RiderMcpHost
    {
        // Builds started via startBuildProject, keyed by buildId, so getBuildStatus
        // can poll them. A build is removed once its terminal status has been read.
        private readonly ConcurrentDictionary<string, SolutionBuilderRequest> myBuilds =
            new ConcurrentDictionary<string, SolutionBuilderRequest>();

        public RiderMcpHost(Lifetime lifetime, ISolution solution)
        {
            var model = solution.GetProtocolSolution().GetRiderMcpModel();

            // Frontend -> backend request handler. SetSync takes a handler that
            // returns the result directly (no RdTask wrapping); the status is
            // built synchronously and cheaply.
            model.GetBackendStatus.SetSync((_, _) => BuildStatus(solution));

            // Build specific project(s). A build can run for minutes, so we DON'T
            // block the RD call for its duration (the frontend/proxy would time
            // out). startBuildProject kicks the build and returns a buildId
            // immediately; getBuildStatus polls that build. Both are cheap/sync.
            model.StartBuildProject.SetSync((_, request) => StartBuild(solution, request));
            model.GetBuildStatus.SetSync((_, buildId) => GetBuildStatus(buildId));

            // Backend -> frontend liveness signal.
            model.BackendReadyChanged.Fire(true);
            lifetime.OnTermination(() => model.BackendReadyChanged.Fire(false));
        }

        /// <summary>
        /// Kicks a build of the requested project(s) through Rider's own build
        /// engine (<see cref="ISolutionBuilder"/>) — the same path as "Build
        /// Selected Project" — and returns a buildId to poll (the build runs in
        /// the background). Returns an empty buildId + message if it can't start.
        /// </summary>
        private BuildStartResult StartBuild(ISolution solution, BuildProjectParams request)
        {
            IEnumerable<IProject> allProjects = solution.GetAllProjects();

            List<IProject> requested = new List<IProject>();
            foreach (string name in request.ProjectNames)
            {
                IProject? match = allProjects.FirstOrDefault(p => string.Equals(p.Name, name, StringComparison.Ordinal));
                if (match != null && !requested.Contains(match))
                    requested.Add(match);
            }

            if (requested.Count == 0)
            {
                string available = string.Join(", ", allProjects.Select(p => p.Name).OrderBy(n => n));
                return new BuildStartResult("",
                    $"No project matched [{string.Join(", ", request.ProjectNames)}]. Available projects: {available}");
            }

            ISolutionBuilder builder = solution.GetComponent<ISolutionBuilder>();
            IBuildSessionTarget target = request.Rebuild ? BuildSessionTarget.Rebuild : BuildSessionTarget.Build;
            SolutionBuilderRequestAdvancedSettings settings = new SolutionBuilderRequestAdvancedSettings
            {
                WithoutDependencies = request.WithoutDependencies,
                IsSingleProjectBuild = requested.Count == 1,
                BuildPurpose = BuildPurpose.BuildOnly,
            };

            SolutionBuilderRequest buildRequest = builder.CreateBuildRequest(
                target, requested, SolutionBuilderRequestSilentMode.Silent, settings);

            string buildId = Guid.NewGuid().ToString();
            myBuilds[buildId] = buildRequest;
            builder.ExecuteBuildRequest(buildRequest); // non-blocking: the build runs in the background
            return new BuildStartResult(buildId, null);
        }

        /// <summary>Snapshots a build's status by buildId (running or final result).</summary>
        private BuildProjectResult GetBuildStatus(string buildId)
        {
            if (!myBuilds.TryGetValue(buildId, out var r))
            {
                return new BuildProjectResult(true, buildId, false, false, false, false, false,
                    new List<string>(), new List<BuildProblem>(), $"Unknown buildId '{buildId}'.");
            }

            bool completed = r.State.Value.HasFlag(BuildRunState.Completed);

            List<BuildProblem> problems = new List<BuildProblem>();
            if (completed)
            {
                try
                {
                    // Errors are offsets into the request's event storage; the
                    // session loader resolves each to a full diagnostic.
                    if (r.SessionLoader is InFileBuildSessionLoader loader)
                    {
                        foreach (BuildEventReference reference in r.GetAllBuildErrors())
                        {
                            BuildEvent ev = loader.LoadEvent(reference.Offset);
                            if (ev == null) continue;
                            string? projectName = reference.ProjectId.HasValue ? r.GetProjectById(reference.ProjectId)?.Name : null;
                            problems.Add(new BuildProblem(ev.Kind.ToString(), ev.Message ?? string.Empty,
                                ev.Code, ev.FilePath, ev.Line, ev.Column, projectName));
                        }
                    }
                }
                catch
                {
                    // Diagnostic resolution is best-effort; the flags below are authoritative.
                }
            }

            List<string> built = r.RequestedProjects.Select(p => p.Project.Name).ToList();
            BuildProjectResult result = new BuildProjectResult(
                completed, buildId,
                r.Succeeded.Value, r.HasErrors.Value, r.HasWarnings.Value, r.HasCancelled.Value, r.Skipped.Value,
                built, problems, null);

            if (completed) myBuilds.TryRemove(buildId, out _); // free the entry once its terminal status is read
            return result;
        }

        private static BackendStatus BuildStatus(ISolution solution)
        {
            var projectCount = solution.GetAllProjects().Count;
            var name = solution.Name ?? solution.SolutionFilePath.NameWithoutExtension;
            var version = typeof(RiderMcpHost).Assembly.GetName().Version?.ToString() ?? "unknown";

            // Positional ctor — field order matches the structdef in :protocol:
            // (solutionName, isReady, projectCount, backendVersion).
            return new BackendStatus(name, true, projectCount, version);
        }
    }
}
