using System;
using System.Collections.Generic;
using System.Linq;
using JetBrains.Application.Parts;
using JetBrains.Lifetimes;
using JetBrains.ProjectModel;
using JetBrains.RdBackend.Common.Features;   // GetProtocolSolution()
using RiderMcp.Model;                          // generated by :protocol rdgen

namespace RiderMcp
{
    /// <summary>
    /// Backend host implementing the RD model declared in :protocol
    /// (<see cref="RiderMcpModel"/>). It answers requests issued by the Kotlin
    /// frontend's MCP tools and announces backend readiness.
    ///
    /// The generated types (RiderMcpModel, BackendStatus, SymbolInfo and the
    /// <c>GetRiderMcpModel()</c> accessor) only resolve after rdgen has run, so
    /// the build wires <c>:protocol:rdgen</c> ahead of compilation.
    /// </summary>
    [SolutionComponent(Instantiation.DemandAnyThreadSafe)]
    public class RiderMcpHost
    {
        public RiderMcpHost(Lifetime lifetime, ISolution solution)
        {
            var model = solution.GetProtocolSolution().GetRiderMcpModel();

            // Frontend -> backend request handlers. The (lifetime, request)
            // lambda overload runs synchronously on the protocol thread; switch
            // to RdTask.Start for work that must go off-thread.
            model.GetBackendStatus.Set((_, _) => BuildStatus(solution));
            model.FindSymbols.Set((_, query) => ResolveSymbols(solution, query));

            // Backend -> frontend liveness signal.
            model.BackendReadyChanged.Fire(true);
            lifetime.OnTermination(() => model.BackendReadyChanged.Fire(false));
        }

        private static BackendStatus BuildStatus(ISolution solution)
        {
            var projectCount = solution.GetAllProjects().Count;
            var name = solution.Name ?? solution.SolutionFilePath.NameWithoutExtension;
            var version = typeof(RiderMcpHost).Assembly.GetName().Version?.ToString() ?? "unknown";

            // Positional ctor — field order matches the structdef in :protocol:
            // (solutionName, isReady, projectCount, backendVersion).
            return new BackendStatus(name, true, projectCount, version);
        }

        private static List<SymbolInfo> ResolveSymbols(ISolution solution, string query)
        {
            var results = new List<SymbolInfo>();
            if (string.IsNullOrWhiteSpace(query))
                return results;

            // ------------------------------------------------------------------
            // TODO: implement real symbol resolution against ReSharper's symbol
            // cache. The shape below is the reference; verify the exact API
            // surface (ISymbolCache / GetSymbolScope / LibrarySymbolScope) against
            // the JetBrains.Rider.SDK version resolved by the build, then map each
            // declared element + its primary declaration's source range.
            //
            //   var cache = solution.GetComponent<ISymbolCache>();
            //   var scope = cache.GetSymbolScope(LibrarySymbolScope.FULL, caseSensitive: false);
            //   foreach (var element in scope.GetElementsByShortName(query))
            //   {
            //       var decl = element.GetDeclarations().FirstOrDefault();
            //       var range = decl?.GetDocumentRange();
            //       results.Add(new SymbolInfo(
            //           fqn:       element.GetClrName()?.FullName ?? element.ShortName,
            //           kind:      element.GetElementType().ToString(),
            //           file:      range?.Document.Moniker ?? "",
            //           line:      range?.StartOffset.ToDocumentCoords().Line.Plus1() ?? 0,
            //           signature: element.ShortName));
            //   }
            // ------------------------------------------------------------------

            return results;
        }
    }
}
